name: Java ausführen

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['11', '16']
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - name: Setup java
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: java -cp java ue_2/HalloWorld/src/com/example/helloworld/
